run:
  concurrency: 2
  timeout: 3m
  issues-exit-code: 1
  tests: true

linters-settings:
  gofmt:
    simplify: true
  lll:
    line-length: 150
    tab-width: 4

linters:
  enable:
    - gofmt
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - unused
    - varcheck
    - structcheck
    - typecheck
    - lll
    - dogsled
    - prealloc
    - unconvert
    - unparam
    - whitespace
    - gomnd
    - testpackage