name: CI
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: ./...
          args: -E golint -E lll -E prealloc -E unconvert -E unparam -E whitespace -E gomnd -E nlreturn -E testpackage  -D deadcode -D varcheck -D unused -D structcheck

      - name: tests
        run: go test ./...

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: 95.163.212.121
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo killall -9 main
            cd 2021_1_BERM && git checkout development && git pull origin development
            sudo go run fl/main.go &>/dev/null&
